In [35]:
import numpy as np 
import pandas as pd

In [36]:
# Create a Pandas Series from a list.
data = [10, 20, 30, 40, 50]
s = pd.Series(data)
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [37]:
# Create a Series with custom indexes. 
data = [10, 20, 30, 40, 50]
s = pd.Series((data), index = ['A', 'B', 'C', 'D', 'E'])
s

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [38]:
# Create a Series from a dictionary. 
data = {
    "Math": 90,
    "Science": 85,
    "English": 88
}
s = pd.Series(data)
s

Math       90
Science    85
English    88
dtype: int64

In [39]:
# Print the first and last element of a Series. 
s = pd.Series([10, 20, 30, 40, 50])

print("First Element:", s.iloc[0])
print("Last Element :", s.iloc[-1])

First Element: 10
Last Element : 50

In [40]:
# Find the dtype, size, shape, and index of a Series.  
s = pd.Series([10, 20, 30, 40, 50])

print("Data Type:", s.dtype)
print("Size     :", s.size)
print("Shape    :", s.shape)
print("Index    :", s.index)

Data Type: int64
Size     : 5
Shape    : (5,)
Index    : RangeIndex(start=0, stop=5, step=1)

In [41]:
# Calculate the sum, mean, maximum, and minimum of a Series. 
s = pd.Series([10, 20, 30, 40, 50])

print("Sum     :", s.sum())
print("Mean    :", s.mean())
print("Maximum :", s.max())
print("Minimum :", s.min())

Sum     : 150
Mean    : 30.0
Maximum : 50
Minimum : 10

In [42]:
# Sort a Series by values. 
s = pd.Series([45, 10, 80, 25, 60])

print(s.sort_values())

1    10
3    25
0    45
4    60
2    80
dtype: int64

In [43]:
# Sort a Series by index.  
s = pd.Series([85, 90, 78],
              index=['C', 'A', 'B'])
print(s.sort_index())

A    90
B    78
C    85
dtype: int64

In [44]:
# Create a DataFrame from a dictionary.  
data = {
    "Name": ["John", "Alice", "Bob"],
    "Age": [25, 30, 28],
    "City": ["New York", "London", "Paris"]
}
df = pd.DataFrame(data)
df

    Name  Age      City
0   John   25  New York
1  Alice   30    London
2    Bob   28     Paris

In [45]:
# Create a DataFrame from a list of lists.  
data = [
    ["Ram", 21, 85],
    ["Shyam", 22, 90],
    ["Mohan", 20, 78]
]

df = pd.DataFrame(data, columns=["Name", "Age", "Marks"])
df

    Name  Age  Marks
0    Ram   21     85
1  Shyam   22     90
2  Mohan   20     78

In [46]:
# Create a DataFrame from a list of dictionaries.  
data = [
    {"Name": "Ram", "Age": 21, "Marks": 85},
    {"Name": "Shyam", "Age": 22, "Marks": 90},
    {"Name": "Mohan", "Age": 20, "Marks": 78}
]
df = pd.DataFrame(data)
df

    Name  Age  Marks
0    Ram   21     85
1  Shyam   22     90
2  Mohan   20     78

In [47]:
# Create a DataFrame with custom indexes. 
data = [
    ["Ram", 21, 85],
    ["Shyam", 22, 90],
    ["Mohan", 20, 78]
]
df = pd.DataFrame(data, columns=["Name", "Age", "Marks"], index=["A", "B", "C"])
df

    Name  Age  Marks
A    Ram   21     85
B  Shyam   22     90
C  Mohan   20     78

In [48]:
# Print the first 5 rows using head().  
data = {
    "Name": ["Ram", "Shyam", "Mohan", "Amit", "Ravi", "Karan"],
    "Marks": [85, 90, 78, 88, 75, 95]
} 
df = pd.DataFrame(data)
print(df.head())

    Name  Marks
0    Ram     85
1  Shyam     90
2  Mohan     78
3   Amit     88
4   Ravi     75

In [49]:
# Print the last 3 rows using tail().  
data = {
    "Name": ["Ram", "Shyam", "Mohan", "Amit", "Ravi", "Karan"],
    "Marks": [85, 90, 78, 88, 75, 95]
} 
df = pd.DataFrame(data)
print(df.tail(3))

    Name  Marks
3   Amit     88
4   Ravi     75
5  Karan     95

In [50]:
# Display dataset information using info()  
data = {
    "Name": ["Ram", "Shyam", "Mohan"],
    "Age": [21, 22, 20],
    "Marks": [85, 90, 78]
}
df = pd.DataFrame(data)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Marks   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [51]:
# Display statistical summary using describe()  
data = {
    "Age": [21, 22, 20, 23, 24],
    "Marks": [85, 90, 78, 88, 95]
}

df = pd.DataFrame(data)
print(df.describe())

             Age      Marks
count   5.000000   5.000000
mean   22.000000  87.200000
std     1.581139   6.300794
min    20.000000  78.000000
25%    21.000000  85.000000
50%    22.000000  88.000000
75%    23.000000  90.000000
max    24.000000  95.000000

In [52]:
# Find the shape of a DataFrame.  
data = {
    "Name": ["Ram", "Shyam", "Mohan"],
    "Age": [21, 22, 20],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

print("Shape:", df.shape)

Shape: (3, 3)

In [53]:
# Find the column names.  
data = {
    "Name": ["Ram", "Shyam", "Mohan"],
    "Age": [21, 22, 20],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

print("column names:", df.columns)

column names: Index(['Name', 'Age', 'Marks'], dtype='object')

In [55]:
# Find the row indexes.  
data = {
    "Name": ["Ram", "Shyam", "Mohan"],
    "Age": [21, 22, 20],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

print("row indexes:", df.index)

row indexes: RangeIndex(start=0, stop=3, step=1)

In [56]:
# Find the data types of all columns.  

data = {
    "Name": ["Ram", "Shyam", "Mohan"],
    "Age": [21, 22, 20],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

print("data types of all columns is:", df.dtypes)

data types of all columns is: Name     object
Age       int64
Marks     int64
dtype: object

In [57]:
# Find the total number of elements.  
data = {
    "Name": ["Ram", "Shyam", "Mohan"],
    "Age": [21, 22, 20],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

print("total number of elements is:", df.size)

total number of elements is: 9

In [58]:
# Convert a DataFrame into a NumPy array using values.  
data = {
    "Name": ["Ram", "Shyam", "Mohan"],
    "Age": [21, 22, 20],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

print("DataFrame into a NumPy array using values:", df.values)

DataFrame into a NumPy array using values: [['Ram' 21 85]
 ['Shyam' 22 90]
 ['Mohan' 20 78]]